require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5

Naming/PredicateName:
  NamePrefix:
  - is_
  AllowedMethods:
  - is_a?
  Exclude:
  - 'spec/**/*'

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
  - http
  - https
  IgnoreCopDirectives: false
  IgnoredPatterns:
  - '\A\s*(remote_)?test(_\w+)?\s.*(do|->)(\s|\Z)'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Rails/HttpPositionalArguments:
  Include:
    - spec/**/*
    - test/**/*

Rails/OutputSafety:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ModuleFunction:
  EnforcedStyle: extend_self

Lint/OrderedMagicComments:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*_spec.rb'
    - '**/spec/support/shared_examples*'
    - '*.gemspec'

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true
