require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

# =============== #
#   Layout Cops   #
# =============== #

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Layout/CaseIndentation:
  EnforcedStyle: end
  AutoCorrect: true
 
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: false
  ForceEqualSignAlignment: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  AutoCorrect: false
  AllowHeredoc: true
  AllowURI: true
  Exclude:
    - spec/**/*.rb
  IgnoreCopDirectives: false
  IgnoredPatterns:
    - '\A\s*(remote_)?test(_\w+)?\s.*(do|->)(\s|\Z)'
  Max: 130
  URISchemes:
    - http
    - https

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

# ================ #
#   Linter Cops   #
# ================ #

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

Lint/BinaryOperatorWithIdenticalOperands: # (0.89)
  Enabled: true 

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException: # (0.89)
  Enabled: true 

Lint/EmptyConditionalBody: # (0.89)
  Enabled: true 

Lint/FloatComparison: # (0.89)
  Enabled: true 

Lint/MissingSuper: # (0.89)
  Enabled: true 
 
Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OrderedMagicComments:
  Enabled: true

Lint/OutOfRangeRegexpRef: # (0.89)
  Enabled: true 

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment: # (0.89)
  Enabled: true 

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument: # (0.89)
  Enabled: true 

Lint/UnreachableLoop: # (0.89)
  Enabled: true 

# TODO: Fix this one
Lint/UriEscapeUnescape:
  Enabled: false

  
# ================ #
#   Metrics Cops   #
# ================ #

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*_spec.rb'
    - '**/spec/support/shared_examples*'
    - '*.gemspec'
    - config/environment/*.rb
    - config/initializers/*.rb
    - spec/**/*.rb

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# ================ #
#   Naming Cops   #
# ================ #

Naming/PredicateName:
  NamePrefix:
  - is_
  AllowedMethods:
  - is_a?
  Exclude:
  - 'spec/**/*'

Naming/VariableNumber:
  EnforcedStyle: non_integer

# ===================
# === Performance ===
# ===================

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

# ================ #
#    Rails Cops    #
# ================ #

Rails/ActiveRecordAliases:
  Enabled: true
  Exclude:
    - lib/forms/**/*.rb
    - spec/lib/forms/**/*.rb

Rails/ActiveRecordCallbacksOrder: # (2.7)
  Enabled: true

Rails/FindById: # (2.7)
  Enabled: true

Rails/Inquiry: # (2.7)
  Enabled: true

Rails/HttpPositionalArguments:
  Include:
    - spec/**/*
    - test/**/*

Rails/MailerName: # (2.7)
  Enabled: true

Rails/MatchRoute: # (2.7)
  Enabled: true

Rails/NegateInclude: # (2.7)
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Pluck: # (2.7)
  Enabled: true

Rails/PluckInWhere: # (2.7)
  Enabled: true

Rails/RenderInline: # (2.7)
  Enabled: true

Rails/RenderPlainText: # (2.7)
  Enabled: true

Rails/ShortI18n: # (2.7)
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - lib/tasks/**/*.rake
    - spec/**/*.rb

Rails/WhereExists: # (2.7)
  Enabled: true

# ================ #
#    RSpec Cops    #
# ================ #

RSpec/ContextWording:
  Enabled: false
  Prefixes:
    - and
    - but
    - for
    - if
    - in
    - unless
    - when
    - with
    - without

RSpec/DescribeClass:
  Exclude:
    - spec/tasks/**/*_spec.rb
    - spec/requests/**/*_spec.rb
    - spec/routing/**/*_spec.rb
    - spec/system/**/*_spec.rb

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/api/**/*_spec.rb

RSpec/ExpectChange:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

# =============== #
#   Style Cops    #
# =============== #


Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument: # (0.89)
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream: # (0.89)
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/OptionalBooleanParameter: # (0.89)
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true
  
Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig: # (0.89)
  Enabled: true
  
Style/SlicingWithRange:
  Enabled: true 
 
Style/StringConcatenation: # (0.89)
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: percent

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: percent

